default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/blog_trainee_development

test:
  <<: *default
  database: db/blog_trainee_test

production:
  <<: *default
  database: db/blog_trainee_production
